name: Lint styles & scripts
on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16

      - name: Setup pnpm ğŸ“¦
        uses: pnpm/action-setup@v2.2.2

      - name: Install dependencies ğŸ”§
        run: |
          pnpm install --frozen-lockfile

      - name: Run eslint âœ¨
        run: |
          node_modules/eslint/bin/eslint.js ./

      - name: Run prettier âœ¨
        run: |
          node_modules/prettier/bin-prettier.js -c ./

      - name: Run stylelint âœ¨
        run: |
          node_modules/stylelint/bin/stylelint.js ./**/*.scss
